configs:
    - configs/base.yaml # default arguments for the whole codebase
    - configs/models/nerft.yaml # network model configuration
    - configs/datasets/NHR/basketball.yaml # dataset usage configuration

# prettier-ignore
exp_name: {{fileBasenameNoExtension}}
