# Configuration for ENeRF
configs:
    - configs/base.yaml # default arguments for the whole codebase
    - configs/models/enerfi.yaml # network model configuration
    - configs/datasets/renbody/0008_01_obj.yaml # dataset usage configuration
    - configs/specs/mask.yaml
    - configs/specs/optimized.yaml

# prettier-ignore
exp_name: {{fileBasenameNoExtension}}
