configs:
    - configs/base.yaml # default arguments for the whole codebase
    - configs/models/enerfi.yaml # network model configuration
    - configs/datasets/enerf_outdoor/actor1_4.yaml # dataset usage configuration
    - configs/specs/static.yaml
    - configs/specs/optimized.yaml

# prettier-ignore
exp_name: {{fileBasenameNoExtension}}
