configs: configs/datasets/mobile_stage/dance3.yaml

dataloader_cfg: &dataloader_cfg
    dataset_cfg: &dataset_cfg # ratio: 0.5
        bounds: [[-2.6625, -2.1826, -1.0188], [0.8725, 0.9999, 1.4587]] # !: BATCH

val_dataloader_cfg:
    <<: *dataloader_cfg
    dataset_cfg:
        <<: *dataset_cfg
