configs: configs/datasets/mobile_stage/white.yaml

dataloader_cfg: &dataloader_cfg
    dataset_cfg: &dataset_cfg # ratio: 0.5
        bounds: [[-1.0213, -0.5813, -1.2888], [0.6887, 0.7587, 0.7512]] # !: BATCH

val_dataloader_cfg:
    <<: *dataloader_cfg
    dataset_cfg:
        <<: *dataset_cfg
