configs: configs/datasets/mobile_stage/xuzhen.yaml

dataloader_cfg: &dataloader_cfg
    dataset_cfg: &dataset_cfg # ratio: 0.5
        bounds: [[-0.6663, -0.6626, -1.2050], [0.5537, 0.4174, 0.8850]] # !: BATCH

val_dataloader_cfg:
    <<: *dataloader_cfg
    dataset_cfg:
        <<: *dataset_cfg
