configs:
    - configs/base.yaml # default arguments for the whole codebase
    - configs/models/ngpt.yaml # network model configuration
    - configs/datasets/renbody/0013_01.yaml # dataset usage configuration
    - configs/specs/static.yaml
    - configs/specs/mask.yaml

# prettier-ignore
exp_name: {{fileBasenameNoExtension}}
