configs:
    - configs/base.yaml # default arguments for the whole codebase
    - configs/models/ngpt.yaml # network model configuration
    - configs/datasets/dtu/scan82.yaml # dataset usage configuration
    - configs/specs/blurry.yaml

# prettier-ignore
exp_name: {{fileBasenameNoExtension}}
