configs:
    - configs/base.yaml # default arguments for the whole codebase
    - configs/models/r4dv.yaml # network model configuration
    - configs/datasets/NHR/sport2_obj.yaml # dataset usage configuration
    - configs/specs/mask.yaml # specific usage configuration
    - configs/specs/prior.yaml # controls some training sampling strategy

# prettier-ignore
exp_name: {{fileBasenameNoExtension}}
