configs: configs/datasets/enerf_outdoor/actor2_3.yaml

dataloader_cfg: &dataloader_cfg
    dataset_cfg: &dataset_cfg # ratio: 0.5
        bounds: [[-0.7050, -0.9850, -1.0150], [1.3450, 0.3050, 0.8750]] # !: BATCH

val_dataloader_cfg:
    <<: *dataloader_cfg
    dataset_cfg:
        <<: *dataset_cfg