val_dataloader_cfg:
    dataset_cfg:
        # prettier-ignore
        frame_sample: {{configs.dataloader_cfg.dataset_cfg.frame_sample}}  # use all images

model_cfg:
    sampler_cfg:
        should_release_memory: False
        # fg_sampler_cfg:
        #     should_release_memory: False
        # bg_sampler_cfg:
        #     should_release_memory: False

runner_cfg:
    visualizer_cfg:
        types: [RENDER] # cudagl does not support depth rendering
