sampler_cfg: &sampler_cfg
    ibr_regressor_cfg:
        sh_mlp_cfg:
            actvn: softplus

model_cfg:
    sampler_cfg:
        <<: *sampler_cfg
        fg_sampler_cfg:
            <<: *sampler_cfg
        bg_sampler_cfg:
            <<: *sampler_cfg
