configs: configs/specs/fp32.yaml # will load the model in fp32 mode

dataloader_cfg: &dataloader_cfg
    dataset_cfg:
        # prettier-ignore
        view_sample: {{configs.dataloader_cfg.dataset_cfg.view_sample}}  # use all images
        # prettier-ignore
        frame_sample: {{configs.dataloader_cfg.dataset_cfg.frame_sample}}  # use all images
    sampler_cfg:
        # prettier-ignore
        view_sample: {{configs.dataloader_cfg.sampler_cfg.view_sample}}  # use all images
        # prettier-ignore
        frame_sample: {{configs.dataloader_cfg.sampler_cfg.frame_sample}}  # use all images

val_dataloader_cfg: *dataloader_cfg

model_cfg:
    sampler_cfg:
        skip_loading_points: True
        pts_per_pix: 15
        compute_dtype: float
        memory_dtype: float
        dtype: float
        use_cudagl: False
        use_diffgl: True
