runner_cfg:
    epochs: 60
    decay_epochs: 30

model_cfg:
    sampler_cfg:
        n_srcs: 8
        pts_per_pix: 64
        radius_shift: -5 # larger when init
        radius_max: 0.25 # 10cm points
        # n_points: 1048576
        points_dir: vhulls # use raw input

dataloader_cfg: &dataloader_cfg
    dataset_cfg: &dataset_cfg
        n_srcs_list: [8]
    batch_sampler_cfg:
        n_srcs_list: [8]

val_dataloader_cfg:
    <<: *dataloader_cfg
    dataset_cfg:
        <<: *dataset_cfg
        # prettier-ignore
        view_sample: {{configs.dataloader_cfg.dataset_cfg.view_sample}}
        extra_src_pool: 16
    sampler_cfg:
        # prettier-ignore
        view_sample: {{configs.val_dataloader_cfg.dataset_cfg.view_sample}}
