model_cfg:
    print_render_progress: False
    renderer_cfg:
        bg_brightness: 0.0
    sampler_cfg:
        bg_brightness: 0.0

val_dataloader_cfg:
    dataset_cfg:
        skip_loading_images: True
        # prettier-ignore
        view_sample: {{configs.dataloader_cfg.dataset_cfg.view_sample}}  # use all images
        # prettier-ignore
        frame_sample: {{configs.dataloader_cfg.dataset_cfg.frame_sample}}  # use all images
    sampler_cfg:
        # prettier-ignore
        view_sample: {{configs.dataloader_cfg.sampler_cfg.view_sample}}  # use all images
        # prettier-ignore
        frame_sample: {{configs.dataloader_cfg.sampler_cfg.frame_sample}}  # use all images
