dataloader_cfg: # we see the term "dataloader" as one word?
    dataset_cfg: &dataset_cfg
        data_root: data/nerfies/toby-sit
        view_sample: [0, 1, 1] # monocular dataset
        frame_sample: [0, null, 1]
        use_aligned_cameras: False
        # Volume based configs
        bounds: [[-2.0, -2.0, -2.0], [2.0, 2.0, 2.0]]
        near: 0.12
        far: 1.60
        # Interpolation related configs
        interp_using_t: True
        closest_using_t: True

val_dataloader_cfg:
    dataset_cfg:
        <<: *dataset_cfg
        view_sample: [0]
        frame_sample: [0, null, 77]
