configs:
    - configs/base.yaml # default arguments for the whole codebase
    - configs/models/enerf.yaml # network model configuration
    - configs/datasets/dtu/scan4.yaml # dataset usage configuration

# prettier-ignore
exp_name: {{fileBasenameNoExtension}}
