configs: configs/datasets/neural3dv/neural3dv.yaml
dataloader_cfg: # we see the term "dataloader" as one word?
    dataset_cfg: &dataset_cfg
        data_root: data/neural3dv/flame_steak

val_dataloader_cfg:
    dataset_cfg:
        <<: *dataset_cfg
